package com.example.myshop.navigation

const val ROUTE_SPLASH = "splash"
const val ROUTE_REGISTER = "register"
const val ROUTE_LOGIN = "login"
const val ROUTE_HOME = "home"
const val ROUTE_CART = "cart"
const val ROUTE_PROFILE = "profile"
const val ROUTE_UPDATE_PRODUCT = "update_product"
const val ROUTE_VIEW_PRODUCT = "view_product"
const val ROUTE_ADMIN_PANEL = "admin_panel"
const val ROUTE_ADD_PRODUCT = "add_product"
const val ROUTE_MANAGE_PRODUCTS = "manage_products"
const val ROUTE_ORDERS = "orders"
const val ROUTE_MANAGE_USERS = "manage_users"
const val ROUTE_SEND_ANNOUNCEMENT = "send_announcement"
const val ROUTE_MAKE_ADMIN =  "make_admin"
const val ROUTE_CATEGORIES = "categories"
const val ROUTE_OFFERS = "offers"
const val ROUTE_ACCOUNT = "account"
